Dependencies:
- 'on': ['@all']
  'require':
    'frameworks/extra-cmake-modules': '@same'
    'frameworks/kwindowsystem' : '@same'
    'frameworks/kconfig' : '@same'
    'frameworks/kcoreaddons' : '@same'
    'kdesupport/phonon' : '@same'
    'third-party/libdbusmenu-qt' : '@same'

Options:
  test-before-installing: True
